-- 코드를 작성해주세요
WITH RECURSIVE AAA AS (
    SELECT
        ID,
        PARENT_ID,
        1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL

    UNION ALL

    SELECT
        E.ID,
        E.PARENT_ID,
        A.GENERATION + 1
    FROM ECOLI_DATA E
    JOIN AAA A
        ON E.PARENT_ID = A.ID
)

SELECT
    COUNT(*) AS COUNT,
    GENERATION
FROM AAA
WHERE ID NOT IN (
    SELECT PARENT_ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NOT NULL
)
GROUP BY GENERATION
ORDER BY GENERATION;