-- 코드를 작성해주세요
SELECT DISTINCT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM DEVELOPERS D
JOIN SKILLCODES S
WHERE (D.SKILL_CODE & (SELECT CODE FROM SKILLCODES S WHERE S.NAME = 'Python') > 0)
OR (D.SKILL_CODE & (SELECT CODE FROM SKILLCODES S WHERE S.NAME = 'C#') > 0)
ORDER BY D.ID